config/routes.rb
Demo::Application.routes.draw do
  
  resources :slides
  resources :roles
  resources :users do
    resources :blogs do
      resources :posts
    end
  end

  namespace :api do
    resources :users
    resources :posts
  end
  
  root :to => "application#index"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :posts
  belongs_to :user
  
  validates_presence_of :user_id
  validates_presence_of :title
  validates_presence_of :description
  
  def serializable_hash(options={})
    super({
      :include => {
        :posts => {}
      }
    }.merge(options))
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  before_filter do
    scoped_user(:user_id)
  end
  
  # GET /blogs
  # GET /blogs.xml
  def index
    
    fancygrid_for :blogs do |grid|
      grid.hidden :id, :user_id
      grid.attributes :title, :description
      grid.rendered :actions
      grid.url = user_blogs_path(scoped_user)
      grid.find do |query|
        query.conditions ["blogs.user_id = ?", scoped_user]
        query.select "*"
      end
    end
    
  end

  # GET /blogs/1
  # GET /blogs/1.xml
  def show
    @blog = Blog.find(params[:id])
    
    fancygrid_for :posts do |grid|
      grid.columns_for :blog do |blog|
        blog.hidden :id, :user_id
        blog.attributes :title
      end
      
      grid.hidden :body
      grid.attributes :id, :blog_id, :title, :description
      grid.rendered :actions
      grid.url = user_blog_posts_path(scoped_user, @blog)
      grid.find do |query|
        query.conditions ["blogs.user_id = ?", scoped_user]
        query.conditions ["posts.blog_id = ?", @blog]
      end
    end

    respond_with @blog
  end

  # GET /blogs/new
  # GET /blogs/new.xml
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.xml
  def create
    @blog = Blog.new(params[:blog])
    @blog.save
    respond_with scoped_user, @blog
  end

  # PUT /blogs/1
  # PUT /blogs/1.xml
  def update
    @blog = Blog.find(params[:id])
    @blog.update_attributes(params[:blog])
    respond_with scoped_user, @blog
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.xml
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    respond_with scoped_user, @blog
  end
end

app/views/blogs/_form.html.haml
:ruby
  scoped = (scoped_user and [scoped_user, blog] or blog)
  
= form_for scoped do |f|
  = render :partial => "shared/errors", :locals => { :record => blog }
  
  - if scoped_user
    = f.hidden_field :user_id, :value => scoped_user.id
  - else
    .field
      = f.label :user_id
      %br
      = collection_select(:blog, :user_id, User.all, :id, :username, :prompt => true)
      
  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :description
    %br
    = f.text_field :description
    
  .actions
    = f.submit

app/views/blogs/edit.html.haml
%h1
  Editing blog

= render :partial => 'form', :locals => { :blog => @blog }

= link_to 'Show', user_blog_path(scoped_user, @blog)
|
= link_to 'Back', user_blogs_path(scoped_user, @blog)

app/views/blogs/index.html.haml
%h1
  Listing blogs

- content_for :fancygrid_buttons do
  = link_to 'New Blog', new_user_blog_path(scoped_user)
  |
  = link_to 'Back', users_path
  
= fancygrid :blogs do |column, record, value|
  - case column.name
  - when :actions
    = link_to "Show", user_blog_path(scoped_user, record)
    |
    = link_to "Edit", edit_user_blog_path(scoped_user, record)
    |
    = link_to "Delete", user_blog_path(scoped_user, record), :method => :delete, :confirm => "Delete?"

app/views/blogs/new.html.haml
%h1
  New blog

= render :partial => 'form', :locals => { :blog => @blog }

= link_to 'Back', user_blogs_path(scoped_user, @blog)

app/views/blogs/show.html.haml
= render :partial => "shared/blog_posts", :locals => { :user => scoped_user, :blog => @blog }