config/routes.rb
Demo::Application.routes.draw do
  
  resources :slides
  resources :roles
  resources :users do
    resources :blogs do
      resources :posts
    end
  end

  namespace :api do
    resources :users
    resources :posts
  end
  
  root :to => "application#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  include ModelExtensions::UserApplyRoles
  
  has_many :blogs
  has_many :posts, :through => :blogs
  has_and_belongs_to_many :roles
  
  validates_presence_of :email
  validates_presence_of :username
  
  def serializable_hash(options={})
    super({
      :include => {
        :roles => {}
      }
    }.merge(options))
  end
  
  def to_pdf
    self.to_xml
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    @users = User.all
    respond_with @users
  end
  
  def show
    @user = User.find_by_id(params[:id])
    respond_with @user
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    fancygrid_for :users do |grid|
      
      grid.hidden :id
      grid.attributes :username, :email
      grid.rendered :actions
      
      grid.url = users_path
      grid.find
    end        
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    respond_with @user
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    respond_with @user
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    @user.save
    respond_with @user
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_with @user
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user
  end
end

app/views/users/_form.html.haml
= form_for user do |f|
  = render :partial => "shared/errors", :locals => { :record => user }
  
  .field
    = f.label :username
    %br
    = f.text_field :username
  .field
    = f.label :email
    %br
    = f.text_field :email
    
  - for role in Role.all
    .field
      = check_box_tag "user[applied_roles][]", role.id, user.roles.include?(role)
      = label_tag role.name
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1
  Editing user

= render :partial => 'form', :locals => { :user => @user }

= link_to 'Back', users_path

app/views/users/index.html.haml
%h1
  Listing users

- content_for :fancygrid_buttons do
  = link_to 'New User', new_user_path
  
= fancygrid :users do |column, record, value|
  - case column.name
  - when :actions
    = link_to "Blogs", user_blogs_path(record)
    |
    = link_to "Edit", edit_user_path(record)
    |
    = link_to "Delete", user_path(record), :method => :delete, :confirm => "Delete?"

app/views/users/new.html.haml
%h1
  New user

= render :partial => 'form', :locals => { :user => @user }

= link_to 'Back', users_path(@user)