config/routes.rb
Demo::Application.routes.draw do
  
  resources :slides
  resources :roles
  resources :users do
    resources :blogs do
      resources :posts
    end
  end

  namespace :api do
    resources :users
    resources :posts
  end
  
  root :to => "application#index"
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  
  validates_presence_of :name
  
  def serializable_hash(options={})
    super({
      :include => {
        :users => {}
      }
    }.merge(options))
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.xml
  def index
    
    fancygrid_for :roles do |grid|
      
      grid.hidden :id
      grid.attributes :name
      grid.rendered :actions
      grid.url = roles_path
      grid.find
      
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])
    
    @role.save
    respond_with @role
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    @role.update_attributes(params[:role])
    respond_with @role
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    
    @role.destroy
    respond_with @role
  end
end

app/views/roles/_form.html.haml
= form_for role do |f|
  = render :partial => "shared/errors", :locals => { :record => role }
  
  .field
    = f.label :name
    %br
    = f.text_field :name
  .actions
    = f.submit

app/views/roles/edit.html.haml
%h1
  Edit role

= render :partial => 'form', :locals => { :role => @role }

= link_to 'Back', roles_path

app/views/roles/index.html.haml
%h1
  Listing roles

- content_for :fancygrid_buttons do
  = link_to 'New Role', new_role_path
  
= fancygrid :roles do |column, record, value|
  - case column.name
  - when :actions
    = link_to "Edit", edit_role_path(record)
    |
    = link_to "Delete", role_path(record), :method => :delete, :confirm => "Delete?"

app/views/roles/new.html.haml
%h1
  New role

= render :partial => 'form', :locals => { :role => @role }

= link_to 'Back', roles_path