config/routes.rb
Demo::Application.routes.draw do
  
  resources :slides
  resources :roles
  resources :users do
    resources :blogs do
      resources :posts
    end
  end

  namespace :api do
    resources :users
    resources :posts
  end
  
  root :to => "application#index"
end

app/views/layouts/application.html.haml
!!! 5
%html( lang="en-US" )
  %head
    
    = stylesheet_link_tag :all
    = javascript_include_tag "jquery-1.4.4.min", "jquery-ui-1.8.12.min", "jrails", "fancygrid", "hotkeys", "application"
    = csrf_meta_tag
    %meta( http-equiv="Content-Type" content="text/html; charset=utf-8" )
    
    /[if lt IE 9]
      :javascript
        document.createElement("nav" );
        document.createElement("header" );
        document.createElement("footer" );
        document.createElement("section" );
        document.createElement("aside" );
        document.createElement("article" );
      
    %title 
      Demo
      
  %body
    %header#page_header
      %h1
        DevCon Demo
      %nav
        %ul
          %li
            = link_to "Home", root_path
          %li
            = link_to "Roles", roles_path
          %li
            = link_to "Users", users_path
            
    %section#page_section
      #js-flash
        - flash.each do |k,v|
          .message{ :class => k }= v
      
      .js-content
        = yield
      
    %footer#page_footer
      Dieses Demoprojekt ist zu finden unter
      = link_to "https://github.com/giniedp/devcon", "https://github.com/giniedp/devcon"
    
:javascript
  $(function(){
    $("#js-flash").bind("mouseenter", function(){ 
      $(this).hide();
    });
    setTimeout ( function(){ $("#js-flash").fadeOut(500); }, 15000 );
  });